if(DEFINED ENV{TARGET_SYS})
  set(TARGET_SYS $ENV{TARGET_SYS})
endif()

if(TARGET_SYS AND NOT ZIG_INIT)
  set(ZIG_INIT ON)
  string(REPLACE "-" ";" TARGETS ${TARGET_SYS})

  list(GET TARGETS 0 ARCH)
  list(GET TARGETS 1 TARGET)

  string(SUBSTRING ${TARGET} 0 1 T1)
  string(TOUPPER ${T1} T1)
  string(SUBSTRING ${TARGET} 1 10 TARGET)
  set(TARGET "${T1}${TARGET}")

  if(${TARGET} STREQUAL Macos)
    set(TARGET Darwin)
  endif()

  set(CMAKE_CROSSCOMPILING ON)
  set(CMAKE_SYSTEM_NAME ${TARGET})
  set(CMAKE_SYSTEM_PROCESSOR ${ARCH})
  message(STATUS "${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")

  include(CMakeForceCompiler)

  set(CMAKE_C_COMPILER_FORCED 1)
  set(CMAKE_C_COMPILER_ID_RUN TRUE)
  set(CMAKE_C_COMPILER "zcc")
  set(CMAKE_C_COMPILER_ID "zig")
  set(CMAKE_C_COMPILER_VERSION 11.0)
  set(CMAKE_C_COMPILER_TARGET   ${TARGET_SYS})
  set(CMAKE_C_FLAGS_INIT "-target ${TARGET_SYS} -O3")

  set(CMAKE_ASM_COMPILER_FORCED 1)
  set(CMAKE_ASM_COMPILER_ID_RUN TRUE)
  set(CMAKE_ASM_COMPILER "zcc")
  set(CMAKE_ASM_COMPILER_ID "zig")
  set(CMAKE_ASM_COMPILER_VERSION 11.0)
  set(CMAKE_ASM_COMPILER_TARGET   ${TARGET_SYS})
  set(CMAKE_ASM_FLAGS_INIT "-target ${TARGET_SYS} -O3")

  set(CMAKE_CXX_COMPILER_FORCED 1)
  set(CMAKE_CXX_COMPILER_ID_RUN TRUE)
  set(CMAKE_CXX_COMPILER "zc++")
  set(CMAKE_CXX_COMPILER_ID "zig")
  set(CMAKE_CXX_COMPILER_VERSION 11.0)
  set(CMAKE_CXX_COMPILER_TARGET   ${TARGET_SYS})
  set(CMAKE_CXX_FLAGS_INIT "-target ${TARGET_SYS} -O3")

  SET(CMAKE_AR "zig")
  SET(CMAKE_RANLIB "ls")

  SET(CMAKE_C_ARCHIVE_CREATE   "<CMAKE_AR> build-lib -target ${TARGET_SYS} --name luajit <LINK_FLAGS> <OBJECTS>")
  SET(CMAKE_C_ARCHIVE_FINISH   "<CMAKE_RANLIB> <TARGET>")

  SET(CMAKE_ASM_ARCHIVE_CREATE ${CMAKE_C_ARCHIVE_CREATE})
  SET(CMAKE_ASM_ARCHIVE_FINISH ${CMAKE_C_ARCHIVE_FINISH})

  SET(CMAKE_CXX_ARCHIVE_CREATE ${CMAKE_C_ARCHIVE_CREATE})
  SET(CMAKE_CXX_ARCHIVE_FINISH ${CMAKE_C_ARCHIVE_FINISH})
endif()
